import type { ReactElement } from "react";
import Blog0, { contentMeta as blogMeta0, contentHeadings as blogHeadings0, contentPlainText as blogPlainText0 } from "../../../content/agent-oriented-thinking-new-mindset-ai-product-teams/index";
import Blog1, { contentMeta as blogMeta1, contentHeadings as blogHeadings1, contentPlainText as blogPlainText1 } from "../../../content/agentic-design-patterns/index";
import Blog2, { contentMeta as blogMeta2, contentHeadings as blogHeadings2, contentPlainText as blogPlainText2 } from "../../../content/agentic-systems-demystified/index";
import Blog3, { contentMeta as blogMeta3, contentHeadings as blogHeadings3, contentPlainText as blogPlainText3 } from "../../../content/ai-developers-new-canvas-architecting-langchain-crewai-langgraph/index";
import Blog4, { contentMeta as blogMeta4, contentHeadings as blogHeadings4, contentPlainText as blogPlainText4 } from "../../../content/apple-scalable-server-model/index";
import Blog5, { contentMeta as blogMeta5, contentHeadings as blogHeadings5, contentPlainText as blogPlainText5 } from "../../../content/automated-batch-processing-pipeline-for-openai-api/index";
import Blog6, { contentMeta as blogMeta6, contentHeadings as blogHeadings6, contentPlainText as blogPlainText6 } from "../../../content/building-personal-data-agents-on-ios/index";
import Blog7, { contentMeta as blogMeta7, contentHeadings as blogHeadings7, contentPlainText as blogPlainText7 } from "../../../content/building-resilient-ai-agents-design-patterns-failure-recovery-guardrails/index";
import Blog8, { contentMeta as blogMeta8, contentHeadings as blogHeadings8, contentPlainText as blogPlainText8 } from "../../../content/business-potential-drive-ux-success/index";
import Blog9, { contentMeta as blogMeta9, contentHeadings as blogHeadings9, contentPlainText as blogPlainText9 } from "../../../content/coding-like-bacteria/index";
import Blog10, { contentMeta as blogMeta10, contentHeadings as blogHeadings10, contentPlainText as blogPlainText10 } from "../../../content/device-rag-system-in-ios-swift/index";
import Blog11, { contentMeta as blogMeta11, contentHeadings as blogHeadings11, contentPlainText as blogPlainText11 } from "../../../content/empowering-intelligent-customer-onboarding-with-hushh-ai/index";
import Blog12, { contentMeta as blogMeta12, contentHeadings as blogHeadings12, contentPlainText as blogPlainText12 } from "../../../content/exploring-untapped-markets-through-ux/index";
import Blog13, { contentMeta as blogMeta13, contentHeadings as blogHeadings13, contentPlainText as blogPlainText13 } from "../../../content/foundation-models-framework/index";
import Blog14, { contentMeta as blogMeta14, contentHeadings as blogHeadings14, contentPlainText as blogPlainText14 } from "../../../content/from-tools-to-agents-why-prompt-engineering-isnt-enough/index";
import Blog15, { contentMeta as blogMeta15, contentHeadings as blogHeadings15, contentPlainText as blogPlainText15 } from "../../../content/gemini-ai-public-data-agent-documentation/index";
import Blog16, { contentMeta as blogMeta16, contentHeadings as blogHeadings16, contentPlainText as blogPlainText16 } from "../../../content/how-personal-knowledge-model-can-simplfy-your-digital-life/index";
import Blog17, { contentMeta as blogMeta17, contentHeadings as blogHeadings17, contentPlainText as blogPlainText17 } from "../../../content/hushh-agents-documentation/index";
import Blog18, { contentMeta as blogMeta18, contentHeadings as blogHeadings18, contentPlainText as blogPlainText18 } from "../../../content/hushh-brand-user-data-query-agent/index";
import Blog19, { contentMeta as blogMeta19, contentHeadings as blogHeadings19, contentPlainText as blogPlainText19 } from "../../../content/hushh-day-zero-story/index";
import Blog20, { contentMeta as blogMeta20, contentHeadings as blogHeadings20, contentPlainText as blogPlainText20 } from "../../../content/hushh-embracing-apple-silicon-for-privacy-first-ai/index";
import Blog21, { contentMeta as blogMeta21, contentHeadings as blogHeadings21, contentPlainText as blogPlainText21 } from "../../../content/hushh-manifesto/index";
import Blog22, { contentMeta as blogMeta22, contentHeadings as blogHeadings22, contentPlainText as blogPlainText22 } from "../../../content/hushh-supabase-profile-creation-agent/index";
import Blog23, { contentMeta as blogMeta23, contentHeadings as blogHeadings23, contentPlainText as blogPlainText23 } from "../../../content/hushh-supabase-profile-update-agent/index";
import Blog24, { contentMeta as blogMeta24, contentHeadings as blogHeadings24, contentPlainText as blogPlainText24 } from "../../../content/hushh-super-intelligence-lab-roles-expectations-compensation/index";
import Blog25, { contentMeta as blogMeta25, contentHeadings as blogHeadings25, contentPlainText as blogPlainText25 } from "../../../content/hushh-user-data-query-agent/index";
import Blog26, { contentMeta as blogMeta26, contentHeadings as blogHeadings26, contentPlainText as blogPlainText26 } from "../../../content/hushh-vibe-search-with-AI/index";
import Blog27, { contentMeta as blogMeta27, contentHeadings as blogHeadings27, contentPlainText as blogPlainText27 } from "../../../content/identify-untapped-opportunity-segments-in-ux/index";
import Blog28, { contentMeta as blogMeta28, contentHeadings as blogHeadings28, contentPlainText as blogPlainText28 } from "../../../content/image-recognition-in-real-life/index";
import Blog29, { contentMeta as blogMeta29, contentHeadings as blogHeadings29, contentPlainText as blogPlainText29 } from "../../../content/implement-batch-processing-using-openAI/index";
import Blog30, { contentMeta as blogMeta30, contentHeadings as blogHeadings30, contentPlainText as blogPlainText30 } from "../../../content/importance-of-business-study-in-ux-research/index";
import Blog31, { contentMeta as blogMeta31, contentHeadings as blogHeadings31, contentPlainText as blogPlainText31 } from "../../../content/industry-trends-on-ux-designs/index";
import Blog32, { contentMeta as blogMeta32, contentHeadings as blogHeadings32, contentPlainText as blogPlainText32 } from "../../../content/inside-apples-compact-on-device-llm/index";
import Blog33, { contentMeta as blogMeta33, contentHeadings as blogHeadings33, contentPlainText as blogPlainText33 } from "../../../content/inside-hushh-tech-kyc-nda-flow/index";
import Blog34, { contentMeta as blogMeta34, contentHeadings as blogHeadings34, contentPlainText as blogPlainText34 } from "../../../content/inside-hushhs-consent-ai-stack/index";
import Blog35, { contentMeta as blogMeta35, contentHeadings as blogHeadings35, contentPlainText as blogPlainText35 } from "../../../content/kai-decision-framework-everyday-markets/index";
import Blog36, { contentMeta as blogMeta36, contentHeadings as blogHeadings36, contentPlainText as blogPlainText36 } from "../../../content/kai-for-every-investor-profile/index";
import Blog37, { contentMeta as blogMeta37, contentHeadings as blogHeadings37, contentPlainText as blogPlainText37 } from "../../../content/kai-less-noise-better-choices/index";
import Blog38, { contentMeta as blogMeta38, contentHeadings as blogHeadings38, contentPlainText as blogPlainText38 } from "../../../content/kai-market-confidence-companion/index";
import Blog39, { contentMeta as blogMeta39, contentHeadings as blogHeadings39, contentPlainText as blogPlainText39 } from "../../../content/logo-analysis-for-brand-affinity/index";
import Blog40, { contentMeta as blogMeta40, contentHeadings as blogHeadings40, contentPlainText as blogPlainText40 } from "../../../content/market-research-in-ux-design/index";
import Blog41, { contentMeta as blogMeta41, contentHeadings as blogHeadings41, contentPlainText as blogPlainText41 } from "../../../content/openai-public-data-agent-documentation/index";
import Blog42, { contentMeta as blogMeta42, contentHeadings as blogHeadings42, contentPlainText as blogPlainText42 } from "../../../content/population-size-matters-in-ux-design-decision/index";
import Blog43, { contentMeta as blogMeta43, contentHeadings as blogHeadings43, contentPlainText as blogPlainText43 } from "../../../content/potential-of-personal-data-monetization/index";
import Blog44, { contentMeta as blogMeta44, contentHeadings as blogHeadings44, contentPlainText as blogPlainText44 } from "../../../content/privacy-by-design/index";
import Blog45, { contentMeta as blogMeta45, contentHeadings as blogHeadings45, contentPlainText as blogPlainText45 } from "../../../content/privacy-first-compliance-kyc-nda/index";
import Blog46, { contentMeta as blogMeta46, contentHeadings as blogHeadings46, contentPlainText as blogPlainText46 } from "../../../content/revolutionize-your-campus-life-with-hushh-for-students/index";
import Blog47, { contentMeta as blogMeta47, contentHeadings as blogHeadings47, contentPlainText as blogPlainText47 } from "../../../content/revolutionizing-shopping-with-hushh-wallet/index";
import Blog48, { contentMeta as blogMeta48, contentHeadings as blogHeadings48, contentPlainText as blogPlainText48 } from "../../../content/search-and-discovery-for-luxury-fashion/index";
import Blog49, { contentMeta as blogMeta49, contentHeadings as blogHeadings49, contentPlainText as blogPlainText49 } from "../../../content/setup-automated-batch-processing-pipline/index";
import Blog50, { contentMeta as blogMeta50, contentHeadings as blogHeadings50, contentPlainText as blogPlainText50 } from "../../../content/seven-foundational-pattern-every-ai-based-system-should-use/index";
import Blog51, { contentMeta as blogMeta51, contentHeadings as blogHeadings51, contentPlainText as blogPlainText51 } from "../../../content/simplifying-gmail-receipt-extraction-for-developers/index";
import Blog52, { contentMeta as blogMeta52, contentHeadings as blogHeadings52, contentPlainText as blogPlainText52 } from "../../../content/summarization-with-ai/index";
import Blog53, { contentMeta as blogMeta53, contentHeadings as blogHeadings53, contentPlainText as blogPlainText53 } from "../../../content/survey-on-language-models/index";
import Blog54, { contentMeta as blogMeta54, contentHeadings as blogHeadings54, contentPlainText as blogPlainText54 } from "../../../content/technology-advancement-in-shaping-ux/index";
import Blog55, { contentMeta as blogMeta55, contentHeadings as blogHeadings55, contentPlainText as blogPlainText55 } from "../../../content/trend-in-ux-future-preparation/index";
import Blog56, { contentMeta as blogMeta56, contentHeadings as blogHeadings56, contentPlainText as blogPlainText56 } from "../../../content/trust-first-kyc-nda-modern-onboarding/index";
import Blog57, { contentMeta as blogMeta57, contentHeadings as blogHeadings57, contentPlainText as blogPlainText57 } from "../../../content/trusted-python-engineering-at-hushh/index";
import Blog58, { contentMeta as blogMeta58, contentHeadings as blogHeadings58, contentPlainText as blogPlainText58 } from "../../../content/understanding-population-size-is-key-to-ux/index";
import Blog59, { contentMeta as blogMeta59, contentHeadings as blogHeadings59, contentPlainText as blogPlainText59 } from "../../../content/unlock-the-power-of-your-data/index";
import Blog60, { contentMeta as blogMeta60, contentHeadings as blogHeadings60, contentPlainText as blogPlainText60 } from "../../../content/unveiling-the-power-and-privacy-of-language-models-in-fashion/index";
import Blog61, { contentMeta as blogMeta61, contentHeadings as blogHeadings61, contentPlainText as blogPlainText61 } from "../../../content/ux-can-boost-business-potential/index";
import Blog62, { contentMeta as blogMeta62, contentHeadings as blogHeadings62, contentPlainText as blogPlainText62 } from "../../../content/voice-to-text-with-whisper/index";
import Blog63, { contentMeta as blogMeta63, contentHeadings as blogHeadings63, contentPlainText as blogPlainText63 } from "../../../content/why-you-need-a-javaScript-module-bundler-in-my-chrome-extensions/index";
import Blog64, { contentMeta as blogMeta64, contentHeadings as blogHeadings64, contentPlainText as blogPlainText64 } from "../../../content/you_dont_need_a_vector_database/index";

export type BlogEntry = {
  _id: string;
  slug: string;
  url: string;
  title: string;
  description: string;
  publishedAt: string;
  updatedAt?: string;
  author?: string;
  tags: string[];
  isPublished: boolean;
  image?: {filePath?: string;};
  headings: Array<{text: string;level: number;slug: string;}>;
  plainText: string;
  body: {raw: string;};
  Content: (props: {components?: Record<string, unknown>;}) => ReactElement;
};

export const allBlogs: BlogEntry[] = [
{
  _id: "agent-oriented-thinking-new-mindset-ai-product-teams",
  slug: "agent-oriented-thinking-new-mindset-ai-product-teams",
  url: "/blogs/agent-oriented-thinking-new-mindset-ai-product-teams",
  title: blogMeta0.title,
  description: blogMeta0.description || "",
  publishedAt: blogMeta0.publishedAt,
  updatedAt: blogMeta0.updatedAt || blogMeta0.publishedAt,
  author: blogMeta0.author || "Hushh Team",
  tags: Array.isArray(blogMeta0.tags) ? blogMeta0.tags : [],
  isPublished: blogMeta0.isPublished !== false,
  image: blogMeta0.image ? { filePath: blogMeta0.image } : undefined,
  headings: blogHeadings0,
  plainText: blogPlainText0,
  body: { raw: blogPlainText0 },
  Content: Blog0
},
{
  _id: "agentic-design-patterns",
  slug: "agentic-design-patterns",
  url: "/blogs/agentic-design-patterns",
  title: blogMeta1.title,
  description: blogMeta1.description || "",
  publishedAt: blogMeta1.publishedAt,
  updatedAt: blogMeta1.updatedAt || blogMeta1.publishedAt,
  author: blogMeta1.author || "Hushh Team",
  tags: Array.isArray(blogMeta1.tags) ? blogMeta1.tags : [],
  isPublished: blogMeta1.isPublished !== false,
  image: blogMeta1.image ? { filePath: blogMeta1.image } : undefined,
  headings: blogHeadings1,
  plainText: blogPlainText1,
  body: { raw: blogPlainText1 },
  Content: Blog1
},
{
  _id: "agentic-systems-demystified",
  slug: "agentic-systems-demystified",
  url: "/blogs/agentic-systems-demystified",
  title: blogMeta2.title,
  description: blogMeta2.description || "",
  publishedAt: blogMeta2.publishedAt,
  updatedAt: blogMeta2.updatedAt || blogMeta2.publishedAt,
  author: blogMeta2.author || "Hushh Team",
  tags: Array.isArray(blogMeta2.tags) ? blogMeta2.tags : [],
  isPublished: blogMeta2.isPublished !== false,
  image: blogMeta2.image ? { filePath: blogMeta2.image } : undefined,
  headings: blogHeadings2,
  plainText: blogPlainText2,
  body: { raw: blogPlainText2 },
  Content: Blog2
},
{
  _id: "ai-developers-new-canvas-architecting-langchain-crewai-langgraph",
  slug: "ai-developers-new-canvas-architecting-langchain-crewai-langgraph",
  url: "/blogs/ai-developers-new-canvas-architecting-langchain-crewai-langgraph",
  title: blogMeta3.title,
  description: blogMeta3.description || "",
  publishedAt: blogMeta3.publishedAt,
  updatedAt: blogMeta3.updatedAt || blogMeta3.publishedAt,
  author: blogMeta3.author || "Hushh Team",
  tags: Array.isArray(blogMeta3.tags) ? blogMeta3.tags : [],
  isPublished: blogMeta3.isPublished !== false,
  image: blogMeta3.image ? { filePath: blogMeta3.image } : undefined,
  headings: blogHeadings3,
  plainText: blogPlainText3,
  body: { raw: blogPlainText3 },
  Content: Blog3
},
{
  _id: "apple-scalable-server-model",
  slug: "apple-scalable-server-model",
  url: "/blogs/apple-scalable-server-model",
  title: blogMeta4.title,
  description: blogMeta4.description || "",
  publishedAt: blogMeta4.publishedAt,
  updatedAt: blogMeta4.updatedAt || blogMeta4.publishedAt,
  author: blogMeta4.author || "Hushh Team",
  tags: Array.isArray(blogMeta4.tags) ? blogMeta4.tags : [],
  isPublished: blogMeta4.isPublished !== false,
  image: blogMeta4.image ? { filePath: blogMeta4.image } : undefined,
  headings: blogHeadings4,
  plainText: blogPlainText4,
  body: { raw: blogPlainText4 },
  Content: Blog4
},
{
  _id: "automated-batch-processing-pipeline-for-openai-api",
  slug: "automated-batch-processing-pipeline-for-openai-api",
  url: "/blogs/automated-batch-processing-pipeline-for-openai-api",
  title: blogMeta5.title,
  description: blogMeta5.description || "",
  publishedAt: blogMeta5.publishedAt,
  updatedAt: blogMeta5.updatedAt || blogMeta5.publishedAt,
  author: blogMeta5.author || "Hushh Team",
  tags: Array.isArray(blogMeta5.tags) ? blogMeta5.tags : [],
  isPublished: blogMeta5.isPublished !== false,
  image: blogMeta5.image ? { filePath: blogMeta5.image } : undefined,
  headings: blogHeadings5,
  plainText: blogPlainText5,
  body: { raw: blogPlainText5 },
  Content: Blog5
},
{
  _id: "building-personal-data-agents-on-ios",
  slug: "building-personal-data-agents-on-ios",
  url: "/blogs/building-personal-data-agents-on-ios",
  title: blogMeta6.title,
  description: blogMeta6.description || "",
  publishedAt: blogMeta6.publishedAt,
  updatedAt: blogMeta6.updatedAt || blogMeta6.publishedAt,
  author: blogMeta6.author || "Hushh Team",
  tags: Array.isArray(blogMeta6.tags) ? blogMeta6.tags : [],
  isPublished: blogMeta6.isPublished !== false,
  image: blogMeta6.image ? { filePath: blogMeta6.image } : undefined,
  headings: blogHeadings6,
  plainText: blogPlainText6,
  body: { raw: blogPlainText6 },
  Content: Blog6
},
{
  _id: "building-resilient-ai-agents-design-patterns-failure-recovery-guardrails",
  slug: "building-resilient-ai-agents-design-patterns-failure-recovery-guardrails",
  url: "/blogs/building-resilient-ai-agents-design-patterns-failure-recovery-guardrails",
  title: blogMeta7.title,
  description: blogMeta7.description || "",
  publishedAt: blogMeta7.publishedAt,
  updatedAt: blogMeta7.updatedAt || blogMeta7.publishedAt,
  author: blogMeta7.author || "Hushh Team",
  tags: Array.isArray(blogMeta7.tags) ? blogMeta7.tags : [],
  isPublished: blogMeta7.isPublished !== false,
  image: blogMeta7.image ? { filePath: blogMeta7.image } : undefined,
  headings: blogHeadings7,
  plainText: blogPlainText7,
  body: { raw: blogPlainText7 },
  Content: Blog7
},
{
  _id: "business-potential-drive-ux-success",
  slug: "business-potential-drive-ux-success",
  url: "/blogs/business-potential-drive-ux-success",
  title: blogMeta8.title,
  description: blogMeta8.description || "",
  publishedAt: blogMeta8.publishedAt,
  updatedAt: blogMeta8.updatedAt || blogMeta8.publishedAt,
  author: blogMeta8.author || "Hushh Team",
  tags: Array.isArray(blogMeta8.tags) ? blogMeta8.tags : [],
  isPublished: blogMeta8.isPublished !== false,
  image: blogMeta8.image ? { filePath: blogMeta8.image } : undefined,
  headings: blogHeadings8,
  plainText: blogPlainText8,
  body: { raw: blogPlainText8 },
  Content: Blog8
},
{
  _id: "coding-like-bacteria",
  slug: "coding-like-bacteria",
  url: "/blogs/coding-like-bacteria",
  title: blogMeta9.title,
  description: blogMeta9.description || "",
  publishedAt: blogMeta9.publishedAt,
  updatedAt: blogMeta9.updatedAt || blogMeta9.publishedAt,
  author: blogMeta9.author || "Hushh Team",
  tags: Array.isArray(blogMeta9.tags) ? blogMeta9.tags : [],
  isPublished: blogMeta9.isPublished !== false,
  image: blogMeta9.image ? { filePath: blogMeta9.image } : undefined,
  headings: blogHeadings9,
  plainText: blogPlainText9,
  body: { raw: blogPlainText9 },
  Content: Blog9
},
{
  _id: "device-rag-system-in-ios-swift",
  slug: "device-rag-system-in-ios-swift",
  url: "/blogs/device-rag-system-in-ios-swift",
  title: blogMeta10.title,
  description: blogMeta10.description || "",
  publishedAt: blogMeta10.publishedAt,
  updatedAt: blogMeta10.updatedAt || blogMeta10.publishedAt,
  author: blogMeta10.author || "Hushh Team",
  tags: Array.isArray(blogMeta10.tags) ? blogMeta10.tags : [],
  isPublished: blogMeta10.isPublished !== false,
  image: blogMeta10.image ? { filePath: blogMeta10.image } : undefined,
  headings: blogHeadings10,
  plainText: blogPlainText10,
  body: { raw: blogPlainText10 },
  Content: Blog10
},
{
  _id: "empowering-intelligent-customer-onboarding-with-hushh-ai",
  slug: "empowering-intelligent-customer-onboarding-with-hushh-ai",
  url: "/blogs/empowering-intelligent-customer-onboarding-with-hushh-ai",
  title: blogMeta11.title,
  description: blogMeta11.description || "",
  publishedAt: blogMeta11.publishedAt,
  updatedAt: blogMeta11.updatedAt || blogMeta11.publishedAt,
  author: blogMeta11.author || "Hushh Team",
  tags: Array.isArray(blogMeta11.tags) ? blogMeta11.tags : [],
  isPublished: blogMeta11.isPublished !== false,
  image: blogMeta11.image ? { filePath: blogMeta11.image } : undefined,
  headings: blogHeadings11,
  plainText: blogPlainText11,
  body: { raw: blogPlainText11 },
  Content: Blog11
},
{
  _id: "exploring-untapped-markets-through-ux",
  slug: "exploring-untapped-markets-through-ux",
  url: "/blogs/exploring-untapped-markets-through-ux",
  title: blogMeta12.title,
  description: blogMeta12.description || "",
  publishedAt: blogMeta12.publishedAt,
  updatedAt: blogMeta12.updatedAt || blogMeta12.publishedAt,
  author: blogMeta12.author || "Hushh Team",
  tags: Array.isArray(blogMeta12.tags) ? blogMeta12.tags : [],
  isPublished: blogMeta12.isPublished !== false,
  image: blogMeta12.image ? { filePath: blogMeta12.image } : undefined,
  headings: blogHeadings12,
  plainText: blogPlainText12,
  body: { raw: blogPlainText12 },
  Content: Blog12
},
{
  _id: "foundation-models-framework",
  slug: "foundation-models-framework",
  url: "/blogs/foundation-models-framework",
  title: blogMeta13.title,
  description: blogMeta13.description || "",
  publishedAt: blogMeta13.publishedAt,
  updatedAt: blogMeta13.updatedAt || blogMeta13.publishedAt,
  author: blogMeta13.author || "Hushh Team",
  tags: Array.isArray(blogMeta13.tags) ? blogMeta13.tags : [],
  isPublished: blogMeta13.isPublished !== false,
  image: blogMeta13.image ? { filePath: blogMeta13.image } : undefined,
  headings: blogHeadings13,
  plainText: blogPlainText13,
  body: { raw: blogPlainText13 },
  Content: Blog13
},
{
  _id: "from-tools-to-agents-why-prompt-engineering-isnt-enough",
  slug: "from-tools-to-agents-why-prompt-engineering-isnt-enough",
  url: "/blogs/from-tools-to-agents-why-prompt-engineering-isnt-enough",
  title: blogMeta14.title,
  description: blogMeta14.description || "",
  publishedAt: blogMeta14.publishedAt,
  updatedAt: blogMeta14.updatedAt || blogMeta14.publishedAt,
  author: blogMeta14.author || "Hushh Team",
  tags: Array.isArray(blogMeta14.tags) ? blogMeta14.tags : [],
  isPublished: blogMeta14.isPublished !== false,
  image: blogMeta14.image ? { filePath: blogMeta14.image } : undefined,
  headings: blogHeadings14,
  plainText: blogPlainText14,
  body: { raw: blogPlainText14 },
  Content: Blog14
},
{
  _id: "gemini-ai-public-data-agent-documentation",
  slug: "gemini-ai-public-data-agent-documentation",
  url: "/blogs/gemini-ai-public-data-agent-documentation",
  title: blogMeta15.title,
  description: blogMeta15.description || "",
  publishedAt: blogMeta15.publishedAt,
  updatedAt: blogMeta15.updatedAt || blogMeta15.publishedAt,
  author: blogMeta15.author || "Hushh Team",
  tags: Array.isArray(blogMeta15.tags) ? blogMeta15.tags : [],
  isPublished: blogMeta15.isPublished !== false,
  image: blogMeta15.image ? { filePath: blogMeta15.image } : undefined,
  headings: blogHeadings15,
  plainText: blogPlainText15,
  body: { raw: blogPlainText15 },
  Content: Blog15
},
{
  _id: "how-personal-knowledge-model-can-simplfy-your-digital-life",
  slug: "how-personal-knowledge-model-can-simplfy-your-digital-life",
  url: "/blogs/how-personal-knowledge-model-can-simplfy-your-digital-life",
  title: blogMeta16.title,
  description: blogMeta16.description || "",
  publishedAt: blogMeta16.publishedAt,
  updatedAt: blogMeta16.updatedAt || blogMeta16.publishedAt,
  author: blogMeta16.author || "Hushh Team",
  tags: Array.isArray(blogMeta16.tags) ? blogMeta16.tags : [],
  isPublished: blogMeta16.isPublished !== false,
  image: blogMeta16.image ? { filePath: blogMeta16.image } : undefined,
  headings: blogHeadings16,
  plainText: blogPlainText16,
  body: { raw: blogPlainText16 },
  Content: Blog16
},
{
  _id: "hushh-agents-documentation",
  slug: "hushh-agents-documentation",
  url: "/blogs/hushh-agents-documentation",
  title: blogMeta17.title,
  description: blogMeta17.description || "",
  publishedAt: blogMeta17.publishedAt,
  updatedAt: blogMeta17.updatedAt || blogMeta17.publishedAt,
  author: blogMeta17.author || "Hushh Team",
  tags: Array.isArray(blogMeta17.tags) ? blogMeta17.tags : [],
  isPublished: blogMeta17.isPublished !== false,
  image: blogMeta17.image ? { filePath: blogMeta17.image } : undefined,
  headings: blogHeadings17,
  plainText: blogPlainText17,
  body: { raw: blogPlainText17 },
  Content: Blog17
},
{
  _id: "hushh-brand-user-data-query-agent",
  slug: "hushh-brand-user-data-query-agent",
  url: "/blogs/hushh-brand-user-data-query-agent",
  title: blogMeta18.title,
  description: blogMeta18.description || "",
  publishedAt: blogMeta18.publishedAt,
  updatedAt: blogMeta18.updatedAt || blogMeta18.publishedAt,
  author: blogMeta18.author || "Hushh Team",
  tags: Array.isArray(blogMeta18.tags) ? blogMeta18.tags : [],
  isPublished: blogMeta18.isPublished !== false,
  image: blogMeta18.image ? { filePath: blogMeta18.image } : undefined,
  headings: blogHeadings18,
  plainText: blogPlainText18,
  body: { raw: blogPlainText18 },
  Content: Blog18
},
{
  _id: "hushh-day-zero-story",
  slug: "hushh-day-zero-story",
  url: "/blogs/hushh-day-zero-story",
  title: blogMeta19.title,
  description: blogMeta19.description || "",
  publishedAt: blogMeta19.publishedAt,
  updatedAt: blogMeta19.updatedAt || blogMeta19.publishedAt,
  author: blogMeta19.author || "Hushh Team",
  tags: Array.isArray(blogMeta19.tags) ? blogMeta19.tags : [],
  isPublished: blogMeta19.isPublished !== false,
  image: blogMeta19.image ? { filePath: blogMeta19.image } : undefined,
  headings: blogHeadings19,
  plainText: blogPlainText19,
  body: { raw: blogPlainText19 },
  Content: Blog19
},
{
  _id: "hushh-embracing-apple-silicon-for-privacy-first-ai",
  slug: "hushh-embracing-apple-silicon-for-privacy-first-ai",
  url: "/blogs/hushh-embracing-apple-silicon-for-privacy-first-ai",
  title: blogMeta20.title,
  description: blogMeta20.description || "",
  publishedAt: blogMeta20.publishedAt,
  updatedAt: blogMeta20.updatedAt || blogMeta20.publishedAt,
  author: blogMeta20.author || "Hushh Team",
  tags: Array.isArray(blogMeta20.tags) ? blogMeta20.tags : [],
  isPublished: blogMeta20.isPublished !== false,
  image: blogMeta20.image ? { filePath: blogMeta20.image } : undefined,
  headings: blogHeadings20,
  plainText: blogPlainText20,
  body: { raw: blogPlainText20 },
  Content: Blog20
},
{
  _id: "hushh-manifesto",
  slug: "hushh-manifesto",
  url: "/blogs/hushh-manifesto",
  title: blogMeta21.title,
  description: blogMeta21.description || "",
  publishedAt: blogMeta21.publishedAt,
  updatedAt: blogMeta21.updatedAt || blogMeta21.publishedAt,
  author: blogMeta21.author || "Hushh Team",
  tags: Array.isArray(blogMeta21.tags) ? blogMeta21.tags : [],
  isPublished: blogMeta21.isPublished !== false,
  image: blogMeta21.image ? { filePath: blogMeta21.image } : undefined,
  headings: blogHeadings21,
  plainText: blogPlainText21,
  body: { raw: blogPlainText21 },
  Content: Blog21
},
{
  _id: "hushh-supabase-profile-creation-agent",
  slug: "hushh-supabase-profile-creation-agent",
  url: "/blogs/hushh-supabase-profile-creation-agent",
  title: blogMeta22.title,
  description: blogMeta22.description || "",
  publishedAt: blogMeta22.publishedAt,
  updatedAt: blogMeta22.updatedAt || blogMeta22.publishedAt,
  author: blogMeta22.author || "Hushh Team",
  tags: Array.isArray(blogMeta22.tags) ? blogMeta22.tags : [],
  isPublished: blogMeta22.isPublished !== false,
  image: blogMeta22.image ? { filePath: blogMeta22.image } : undefined,
  headings: blogHeadings22,
  plainText: blogPlainText22,
  body: { raw: blogPlainText22 },
  Content: Blog22
},
{
  _id: "hushh-supabase-profile-update-agent",
  slug: "hushh-supabase-profile-update-agent",
  url: "/blogs/hushh-supabase-profile-update-agent",
  title: blogMeta23.title,
  description: blogMeta23.description || "",
  publishedAt: blogMeta23.publishedAt,
  updatedAt: blogMeta23.updatedAt || blogMeta23.publishedAt,
  author: blogMeta23.author || "Hushh Team",
  tags: Array.isArray(blogMeta23.tags) ? blogMeta23.tags : [],
  isPublished: blogMeta23.isPublished !== false,
  image: blogMeta23.image ? { filePath: blogMeta23.image } : undefined,
  headings: blogHeadings23,
  plainText: blogPlainText23,
  body: { raw: blogPlainText23 },
  Content: Blog23
},
{
  _id: "hushh-super-intelligence-lab-roles-expectations-compensation",
  slug: "hushh-super-intelligence-lab-roles-expectations-compensation",
  url: "/blogs/hushh-super-intelligence-lab-roles-expectations-compensation",
  title: blogMeta24.title,
  description: blogMeta24.description || "",
  publishedAt: blogMeta24.publishedAt,
  updatedAt: blogMeta24.updatedAt || blogMeta24.publishedAt,
  author: blogMeta24.author || "Hushh Team",
  tags: Array.isArray(blogMeta24.tags) ? blogMeta24.tags : [],
  isPublished: blogMeta24.isPublished !== false,
  image: blogMeta24.image ? { filePath: blogMeta24.image } : undefined,
  headings: blogHeadings24,
  plainText: blogPlainText24,
  body: { raw: blogPlainText24 },
  Content: Blog24
},
{
  _id: "hushh-user-data-query-agent",
  slug: "hushh-user-data-query-agent",
  url: "/blogs/hushh-user-data-query-agent",
  title: blogMeta25.title,
  description: blogMeta25.description || "",
  publishedAt: blogMeta25.publishedAt,
  updatedAt: blogMeta25.updatedAt || blogMeta25.publishedAt,
  author: blogMeta25.author || "Hushh Team",
  tags: Array.isArray(blogMeta25.tags) ? blogMeta25.tags : [],
  isPublished: blogMeta25.isPublished !== false,
  image: blogMeta25.image ? { filePath: blogMeta25.image } : undefined,
  headings: blogHeadings25,
  plainText: blogPlainText25,
  body: { raw: blogPlainText25 },
  Content: Blog25
},
{
  _id: "hushh-vibe-search-with-AI",
  slug: "hushh-vibe-search-with-AI",
  url: "/blogs/hushh-vibe-search-with-AI",
  title: blogMeta26.title,
  description: blogMeta26.description || "",
  publishedAt: blogMeta26.publishedAt,
  updatedAt: blogMeta26.updatedAt || blogMeta26.publishedAt,
  author: blogMeta26.author || "Hushh Team",
  tags: Array.isArray(blogMeta26.tags) ? blogMeta26.tags : [],
  isPublished: blogMeta26.isPublished !== false,
  image: blogMeta26.image ? { filePath: blogMeta26.image } : undefined,
  headings: blogHeadings26,
  plainText: blogPlainText26,
  body: { raw: blogPlainText26 },
  Content: Blog26
},
{
  _id: "identify-untapped-opportunity-segments-in-ux",
  slug: "identify-untapped-opportunity-segments-in-ux",
  url: "/blogs/identify-untapped-opportunity-segments-in-ux",
  title: blogMeta27.title,
  description: blogMeta27.description || "",
  publishedAt: blogMeta27.publishedAt,
  updatedAt: blogMeta27.updatedAt || blogMeta27.publishedAt,
  author: blogMeta27.author || "Hushh Team",
  tags: Array.isArray(blogMeta27.tags) ? blogMeta27.tags : [],
  isPublished: blogMeta27.isPublished !== false,
  image: blogMeta27.image ? { filePath: blogMeta27.image } : undefined,
  headings: blogHeadings27,
  plainText: blogPlainText27,
  body: { raw: blogPlainText27 },
  Content: Blog27
},
{
  _id: "image-recognition-in-real-life",
  slug: "image-recognition-in-real-life",
  url: "/blogs/image-recognition-in-real-life",
  title: blogMeta28.title,
  description: blogMeta28.description || "",
  publishedAt: blogMeta28.publishedAt,
  updatedAt: blogMeta28.updatedAt || blogMeta28.publishedAt,
  author: blogMeta28.author || "Hushh Team",
  tags: Array.isArray(blogMeta28.tags) ? blogMeta28.tags : [],
  isPublished: blogMeta28.isPublished !== false,
  image: blogMeta28.image ? { filePath: blogMeta28.image } : undefined,
  headings: blogHeadings28,
  plainText: blogPlainText28,
  body: { raw: blogPlainText28 },
  Content: Blog28
},
{
  _id: "implement-batch-processing-using-openAI",
  slug: "implement-batch-processing-using-openAI",
  url: "/blogs/implement-batch-processing-using-openAI",
  title: blogMeta29.title,
  description: blogMeta29.description || "",
  publishedAt: blogMeta29.publishedAt,
  updatedAt: blogMeta29.updatedAt || blogMeta29.publishedAt,
  author: blogMeta29.author || "Hushh Team",
  tags: Array.isArray(blogMeta29.tags) ? blogMeta29.tags : [],
  isPublished: blogMeta29.isPublished !== false,
  image: blogMeta29.image ? { filePath: blogMeta29.image } : undefined,
  headings: blogHeadings29,
  plainText: blogPlainText29,
  body: { raw: blogPlainText29 },
  Content: Blog29
},
{
  _id: "importance-of-business-study-in-ux-research",
  slug: "importance-of-business-study-in-ux-research",
  url: "/blogs/importance-of-business-study-in-ux-research",
  title: blogMeta30.title,
  description: blogMeta30.description || "",
  publishedAt: blogMeta30.publishedAt,
  updatedAt: blogMeta30.updatedAt || blogMeta30.publishedAt,
  author: blogMeta30.author || "Hushh Team",
  tags: Array.isArray(blogMeta30.tags) ? blogMeta30.tags : [],
  isPublished: blogMeta30.isPublished !== false,
  image: blogMeta30.image ? { filePath: blogMeta30.image } : undefined,
  headings: blogHeadings30,
  plainText: blogPlainText30,
  body: { raw: blogPlainText30 },
  Content: Blog30
},
{
  _id: "industry-trends-on-ux-designs",
  slug: "industry-trends-on-ux-designs",
  url: "/blogs/industry-trends-on-ux-designs",
  title: blogMeta31.title,
  description: blogMeta31.description || "",
  publishedAt: blogMeta31.publishedAt,
  updatedAt: blogMeta31.updatedAt || blogMeta31.publishedAt,
  author: blogMeta31.author || "Hushh Team",
  tags: Array.isArray(blogMeta31.tags) ? blogMeta31.tags : [],
  isPublished: blogMeta31.isPublished !== false,
  image: blogMeta31.image ? { filePath: blogMeta31.image } : undefined,
  headings: blogHeadings31,
  plainText: blogPlainText31,
  body: { raw: blogPlainText31 },
  Content: Blog31
},
{
  _id: "inside-apples-compact-on-device-llm",
  slug: "inside-apples-compact-on-device-llm",
  url: "/blogs/inside-apples-compact-on-device-llm",
  title: blogMeta32.title,
  description: blogMeta32.description || "",
  publishedAt: blogMeta32.publishedAt,
  updatedAt: blogMeta32.updatedAt || blogMeta32.publishedAt,
  author: blogMeta32.author || "Hushh Team",
  tags: Array.isArray(blogMeta32.tags) ? blogMeta32.tags : [],
  isPublished: blogMeta32.isPublished !== false,
  image: blogMeta32.image ? { filePath: blogMeta32.image } : undefined,
  headings: blogHeadings32,
  plainText: blogPlainText32,
  body: { raw: blogPlainText32 },
  Content: Blog32
},
{
  _id: "inside-hushh-tech-kyc-nda-flow",
  slug: "inside-hushh-tech-kyc-nda-flow",
  url: "/blogs/inside-hushh-tech-kyc-nda-flow",
  title: blogMeta33.title,
  description: blogMeta33.description || "",
  publishedAt: blogMeta33.publishedAt,
  updatedAt: blogMeta33.updatedAt || blogMeta33.publishedAt,
  author: blogMeta33.author || "Hushh Team",
  tags: Array.isArray(blogMeta33.tags) ? blogMeta33.tags : [],
  isPublished: blogMeta33.isPublished !== false,
  image: blogMeta33.image ? { filePath: blogMeta33.image } : undefined,
  headings: blogHeadings33,
  plainText: blogPlainText33,
  body: { raw: blogPlainText33 },
  Content: Blog33
},
{
  _id: "inside-hushhs-consent-ai-stack",
  slug: "inside-hushhs-consent-ai-stack",
  url: "/blogs/inside-hushhs-consent-ai-stack",
  title: blogMeta34.title,
  description: blogMeta34.description || "",
  publishedAt: blogMeta34.publishedAt,
  updatedAt: blogMeta34.updatedAt || blogMeta34.publishedAt,
  author: blogMeta34.author || "Hushh Team",
  tags: Array.isArray(blogMeta34.tags) ? blogMeta34.tags : [],
  isPublished: blogMeta34.isPublished !== false,
  image: blogMeta34.image ? { filePath: blogMeta34.image } : undefined,
  headings: blogHeadings34,
  plainText: blogPlainText34,
  body: { raw: blogPlainText34 },
  Content: Blog34
},
{
  _id: "kai-decision-framework-everyday-markets",
  slug: "kai-decision-framework-everyday-markets",
  url: "/blogs/kai-decision-framework-everyday-markets",
  title: blogMeta35.title,
  description: blogMeta35.description || "",
  publishedAt: blogMeta35.publishedAt,
  updatedAt: blogMeta35.updatedAt || blogMeta35.publishedAt,
  author: blogMeta35.author || "Hushh Team",
  tags: Array.isArray(blogMeta35.tags) ? blogMeta35.tags : [],
  isPublished: blogMeta35.isPublished !== false,
  image: blogMeta35.image ? { filePath: blogMeta35.image } : undefined,
  headings: blogHeadings35,
  plainText: blogPlainText35,
  body: { raw: blogPlainText35 },
  Content: Blog35
},
{
  _id: "kai-for-every-investor-profile",
  slug: "kai-for-every-investor-profile",
  url: "/blogs/kai-for-every-investor-profile",
  title: blogMeta36.title,
  description: blogMeta36.description || "",
  publishedAt: blogMeta36.publishedAt,
  updatedAt: blogMeta36.updatedAt || blogMeta36.publishedAt,
  author: blogMeta36.author || "Hushh Team",
  tags: Array.isArray(blogMeta36.tags) ? blogMeta36.tags : [],
  isPublished: blogMeta36.isPublished !== false,
  image: blogMeta36.image ? { filePath: blogMeta36.image } : undefined,
  headings: blogHeadings36,
  plainText: blogPlainText36,
  body: { raw: blogPlainText36 },
  Content: Blog36
},
{
  _id: "kai-less-noise-better-choices",
  slug: "kai-less-noise-better-choices",
  url: "/blogs/kai-less-noise-better-choices",
  title: blogMeta37.title,
  description: blogMeta37.description || "",
  publishedAt: blogMeta37.publishedAt,
  updatedAt: blogMeta37.updatedAt || blogMeta37.publishedAt,
  author: blogMeta37.author || "Hushh Team",
  tags: Array.isArray(blogMeta37.tags) ? blogMeta37.tags : [],
  isPublished: blogMeta37.isPublished !== false,
  image: blogMeta37.image ? { filePath: blogMeta37.image } : undefined,
  headings: blogHeadings37,
  plainText: blogPlainText37,
  body: { raw: blogPlainText37 },
  Content: Blog37
},
{
  _id: "kai-market-confidence-companion",
  slug: "kai-market-confidence-companion",
  url: "/blogs/kai-market-confidence-companion",
  title: blogMeta38.title,
  description: blogMeta38.description || "",
  publishedAt: blogMeta38.publishedAt,
  updatedAt: blogMeta38.updatedAt || blogMeta38.publishedAt,
  author: blogMeta38.author || "Hushh Team",
  tags: Array.isArray(blogMeta38.tags) ? blogMeta38.tags : [],
  isPublished: blogMeta38.isPublished !== false,
  image: blogMeta38.image ? { filePath: blogMeta38.image } : undefined,
  headings: blogHeadings38,
  plainText: blogPlainText38,
  body: { raw: blogPlainText38 },
  Content: Blog38
},
{
  _id: "logo-analysis-for-brand-affinity",
  slug: "logo-analysis-for-brand-affinity",
  url: "/blogs/logo-analysis-for-brand-affinity",
  title: blogMeta39.title,
  description: blogMeta39.description || "",
  publishedAt: blogMeta39.publishedAt,
  updatedAt: blogMeta39.updatedAt || blogMeta39.publishedAt,
  author: blogMeta39.author || "Hushh Team",
  tags: Array.isArray(blogMeta39.tags) ? blogMeta39.tags : [],
  isPublished: blogMeta39.isPublished !== false,
  image: blogMeta39.image ? { filePath: blogMeta39.image } : undefined,
  headings: blogHeadings39,
  plainText: blogPlainText39,
  body: { raw: blogPlainText39 },
  Content: Blog39
},
{
  _id: "market-research-in-ux-design",
  slug: "market-research-in-ux-design",
  url: "/blogs/market-research-in-ux-design",
  title: blogMeta40.title,
  description: blogMeta40.description || "",
  publishedAt: blogMeta40.publishedAt,
  updatedAt: blogMeta40.updatedAt || blogMeta40.publishedAt,
  author: blogMeta40.author || "Hushh Team",
  tags: Array.isArray(blogMeta40.tags) ? blogMeta40.tags : [],
  isPublished: blogMeta40.isPublished !== false,
  image: blogMeta40.image ? { filePath: blogMeta40.image } : undefined,
  headings: blogHeadings40,
  plainText: blogPlainText40,
  body: { raw: blogPlainText40 },
  Content: Blog40
},
{
  _id: "openai-public-data-agent-documentation",
  slug: "openai-public-data-agent-documentation",
  url: "/blogs/openai-public-data-agent-documentation",
  title: blogMeta41.title,
  description: blogMeta41.description || "",
  publishedAt: blogMeta41.publishedAt,
  updatedAt: blogMeta41.updatedAt || blogMeta41.publishedAt,
  author: blogMeta41.author || "Hushh Team",
  tags: Array.isArray(blogMeta41.tags) ? blogMeta41.tags : [],
  isPublished: blogMeta41.isPublished !== false,
  image: blogMeta41.image ? { filePath: blogMeta41.image } : undefined,
  headings: blogHeadings41,
  plainText: blogPlainText41,
  body: { raw: blogPlainText41 },
  Content: Blog41
},
{
  _id: "population-size-matters-in-ux-design-decision",
  slug: "population-size-matters-in-ux-design-decision",
  url: "/blogs/population-size-matters-in-ux-design-decision",
  title: blogMeta42.title,
  description: blogMeta42.description || "",
  publishedAt: blogMeta42.publishedAt,
  updatedAt: blogMeta42.updatedAt || blogMeta42.publishedAt,
  author: blogMeta42.author || "Hushh Team",
  tags: Array.isArray(blogMeta42.tags) ? blogMeta42.tags : [],
  isPublished: blogMeta42.isPublished !== false,
  image: blogMeta42.image ? { filePath: blogMeta42.image } : undefined,
  headings: blogHeadings42,
  plainText: blogPlainText42,
  body: { raw: blogPlainText42 },
  Content: Blog42
},
{
  _id: "potential-of-personal-data-monetization",
  slug: "potential-of-personal-data-monetization",
  url: "/blogs/potential-of-personal-data-monetization",
  title: blogMeta43.title,
  description: blogMeta43.description || "",
  publishedAt: blogMeta43.publishedAt,
  updatedAt: blogMeta43.updatedAt || blogMeta43.publishedAt,
  author: blogMeta43.author || "Hushh Team",
  tags: Array.isArray(blogMeta43.tags) ? blogMeta43.tags : [],
  isPublished: blogMeta43.isPublished !== false,
  image: blogMeta43.image ? { filePath: blogMeta43.image } : undefined,
  headings: blogHeadings43,
  plainText: blogPlainText43,
  body: { raw: blogPlainText43 },
  Content: Blog43
},
{
  _id: "privacy-by-design",
  slug: "privacy-by-design",
  url: "/blogs/privacy-by-design",
  title: blogMeta44.title,
  description: blogMeta44.description || "",
  publishedAt: blogMeta44.publishedAt,
  updatedAt: blogMeta44.updatedAt || blogMeta44.publishedAt,
  author: blogMeta44.author || "Hushh Team",
  tags: Array.isArray(blogMeta44.tags) ? blogMeta44.tags : [],
  isPublished: blogMeta44.isPublished !== false,
  image: blogMeta44.image ? { filePath: blogMeta44.image } : undefined,
  headings: blogHeadings44,
  plainText: blogPlainText44,
  body: { raw: blogPlainText44 },
  Content: Blog44
},
{
  _id: "privacy-first-compliance-kyc-nda",
  slug: "privacy-first-compliance-kyc-nda",
  url: "/blogs/privacy-first-compliance-kyc-nda",
  title: blogMeta45.title,
  description: blogMeta45.description || "",
  publishedAt: blogMeta45.publishedAt,
  updatedAt: blogMeta45.updatedAt || blogMeta45.publishedAt,
  author: blogMeta45.author || "Hushh Team",
  tags: Array.isArray(blogMeta45.tags) ? blogMeta45.tags : [],
  isPublished: blogMeta45.isPublished !== false,
  image: blogMeta45.image ? { filePath: blogMeta45.image } : undefined,
  headings: blogHeadings45,
  plainText: blogPlainText45,
  body: { raw: blogPlainText45 },
  Content: Blog45
},
{
  _id: "revolutionize-your-campus-life-with-hushh-for-students",
  slug: "revolutionize-your-campus-life-with-hushh-for-students",
  url: "/blogs/revolutionize-your-campus-life-with-hushh-for-students",
  title: blogMeta46.title,
  description: blogMeta46.description || "",
  publishedAt: blogMeta46.publishedAt,
  updatedAt: blogMeta46.updatedAt || blogMeta46.publishedAt,
  author: blogMeta46.author || "Hushh Team",
  tags: Array.isArray(blogMeta46.tags) ? blogMeta46.tags : [],
  isPublished: blogMeta46.isPublished !== false,
  image: blogMeta46.image ? { filePath: blogMeta46.image } : undefined,
  headings: blogHeadings46,
  plainText: blogPlainText46,
  body: { raw: blogPlainText46 },
  Content: Blog46
},
{
  _id: "revolutionizing-shopping-with-hushh-wallet",
  slug: "revolutionizing-shopping-with-hushh-wallet",
  url: "/blogs/revolutionizing-shopping-with-hushh-wallet",
  title: blogMeta47.title,
  description: blogMeta47.description || "",
  publishedAt: blogMeta47.publishedAt,
  updatedAt: blogMeta47.updatedAt || blogMeta47.publishedAt,
  author: blogMeta47.author || "Hushh Team",
  tags: Array.isArray(blogMeta47.tags) ? blogMeta47.tags : [],
  isPublished: blogMeta47.isPublished !== false,
  image: blogMeta47.image ? { filePath: blogMeta47.image } : undefined,
  headings: blogHeadings47,
  plainText: blogPlainText47,
  body: { raw: blogPlainText47 },
  Content: Blog47
},
{
  _id: "search-and-discovery-for-luxury-fashion",
  slug: "search-and-discovery-for-luxury-fashion",
  url: "/blogs/search-and-discovery-for-luxury-fashion",
  title: blogMeta48.title,
  description: blogMeta48.description || "",
  publishedAt: blogMeta48.publishedAt,
  updatedAt: blogMeta48.updatedAt || blogMeta48.publishedAt,
  author: blogMeta48.author || "Hushh Team",
  tags: Array.isArray(blogMeta48.tags) ? blogMeta48.tags : [],
  isPublished: blogMeta48.isPublished !== false,
  image: blogMeta48.image ? { filePath: blogMeta48.image } : undefined,
  headings: blogHeadings48,
  plainText: blogPlainText48,
  body: { raw: blogPlainText48 },
  Content: Blog48
},
{
  _id: "setup-automated-batch-processing-pipline",
  slug: "setup-automated-batch-processing-pipline",
  url: "/blogs/setup-automated-batch-processing-pipline",
  title: blogMeta49.title,
  description: blogMeta49.description || "",
  publishedAt: blogMeta49.publishedAt,
  updatedAt: blogMeta49.updatedAt || blogMeta49.publishedAt,
  author: blogMeta49.author || "Hushh Team",
  tags: Array.isArray(blogMeta49.tags) ? blogMeta49.tags : [],
  isPublished: blogMeta49.isPublished !== false,
  image: blogMeta49.image ? { filePath: blogMeta49.image } : undefined,
  headings: blogHeadings49,
  plainText: blogPlainText49,
  body: { raw: blogPlainText49 },
  Content: Blog49
},
{
  _id: "seven-foundational-pattern-every-ai-based-system-should-use",
  slug: "seven-foundational-pattern-every-ai-based-system-should-use",
  url: "/blogs/seven-foundational-pattern-every-ai-based-system-should-use",
  title: blogMeta50.title,
  description: blogMeta50.description || "",
  publishedAt: blogMeta50.publishedAt,
  updatedAt: blogMeta50.updatedAt || blogMeta50.publishedAt,
  author: blogMeta50.author || "Hushh Team",
  tags: Array.isArray(blogMeta50.tags) ? blogMeta50.tags : [],
  isPublished: blogMeta50.isPublished !== false,
  image: blogMeta50.image ? { filePath: blogMeta50.image } : undefined,
  headings: blogHeadings50,
  plainText: blogPlainText50,
  body: { raw: blogPlainText50 },
  Content: Blog50
},
{
  _id: "simplifying-gmail-receipt-extraction-for-developers",
  slug: "simplifying-gmail-receipt-extraction-for-developers",
  url: "/blogs/simplifying-gmail-receipt-extraction-for-developers",
  title: blogMeta51.title,
  description: blogMeta51.description || "",
  publishedAt: blogMeta51.publishedAt,
  updatedAt: blogMeta51.updatedAt || blogMeta51.publishedAt,
  author: blogMeta51.author || "Hushh Team",
  tags: Array.isArray(blogMeta51.tags) ? blogMeta51.tags : [],
  isPublished: blogMeta51.isPublished !== false,
  image: blogMeta51.image ? { filePath: blogMeta51.image } : undefined,
  headings: blogHeadings51,
  plainText: blogPlainText51,
  body: { raw: blogPlainText51 },
  Content: Blog51
},
{
  _id: "summarization-with-ai",
  slug: "summarization-with-ai",
  url: "/blogs/summarization-with-ai",
  title: blogMeta52.title,
  description: blogMeta52.description || "",
  publishedAt: blogMeta52.publishedAt,
  updatedAt: blogMeta52.updatedAt || blogMeta52.publishedAt,
  author: blogMeta52.author || "Hushh Team",
  tags: Array.isArray(blogMeta52.tags) ? blogMeta52.tags : [],
  isPublished: blogMeta52.isPublished !== false,
  image: blogMeta52.image ? { filePath: blogMeta52.image } : undefined,
  headings: blogHeadings52,
  plainText: blogPlainText52,
  body: { raw: blogPlainText52 },
  Content: Blog52
},
{
  _id: "survey-on-language-models",
  slug: "survey-on-language-models",
  url: "/blogs/survey-on-language-models",
  title: blogMeta53.title,
  description: blogMeta53.description || "",
  publishedAt: blogMeta53.publishedAt,
  updatedAt: blogMeta53.updatedAt || blogMeta53.publishedAt,
  author: blogMeta53.author || "Hushh Team",
  tags: Array.isArray(blogMeta53.tags) ? blogMeta53.tags : [],
  isPublished: blogMeta53.isPublished !== false,
  image: blogMeta53.image ? { filePath: blogMeta53.image } : undefined,
  headings: blogHeadings53,
  plainText: blogPlainText53,
  body: { raw: blogPlainText53 },
  Content: Blog53
},
{
  _id: "technology-advancement-in-shaping-ux",
  slug: "technology-advancement-in-shaping-ux",
  url: "/blogs/technology-advancement-in-shaping-ux",
  title: blogMeta54.title,
  description: blogMeta54.description || "",
  publishedAt: blogMeta54.publishedAt,
  updatedAt: blogMeta54.updatedAt || blogMeta54.publishedAt,
  author: blogMeta54.author || "Hushh Team",
  tags: Array.isArray(blogMeta54.tags) ? blogMeta54.tags : [],
  isPublished: blogMeta54.isPublished !== false,
  image: blogMeta54.image ? { filePath: blogMeta54.image } : undefined,
  headings: blogHeadings54,
  plainText: blogPlainText54,
  body: { raw: blogPlainText54 },
  Content: Blog54
},
{
  _id: "trend-in-ux-future-preparation",
  slug: "trend-in-ux-future-preparation",
  url: "/blogs/trend-in-ux-future-preparation",
  title: blogMeta55.title,
  description: blogMeta55.description || "",
  publishedAt: blogMeta55.publishedAt,
  updatedAt: blogMeta55.updatedAt || blogMeta55.publishedAt,
  author: blogMeta55.author || "Hushh Team",
  tags: Array.isArray(blogMeta55.tags) ? blogMeta55.tags : [],
  isPublished: blogMeta55.isPublished !== false,
  image: blogMeta55.image ? { filePath: blogMeta55.image } : undefined,
  headings: blogHeadings55,
  plainText: blogPlainText55,
  body: { raw: blogPlainText55 },
  Content: Blog55
},
{
  _id: "trust-first-kyc-nda-modern-onboarding",
  slug: "trust-first-kyc-nda-modern-onboarding",
  url: "/blogs/trust-first-kyc-nda-modern-onboarding",
  title: blogMeta56.title,
  description: blogMeta56.description || "",
  publishedAt: blogMeta56.publishedAt,
  updatedAt: blogMeta56.updatedAt || blogMeta56.publishedAt,
  author: blogMeta56.author || "Hushh Team",
  tags: Array.isArray(blogMeta56.tags) ? blogMeta56.tags : [],
  isPublished: blogMeta56.isPublished !== false,
  image: blogMeta56.image ? { filePath: blogMeta56.image } : undefined,
  headings: blogHeadings56,
  plainText: blogPlainText56,
  body: { raw: blogPlainText56 },
  Content: Blog56
},
{
  _id: "trusted-python-engineering-at-hushh",
  slug: "trusted-python-engineering-at-hushh",
  url: "/blogs/trusted-python-engineering-at-hushh",
  title: blogMeta57.title,
  description: blogMeta57.description || "",
  publishedAt: blogMeta57.publishedAt,
  updatedAt: blogMeta57.updatedAt || blogMeta57.publishedAt,
  author: blogMeta57.author || "Hushh Team",
  tags: Array.isArray(blogMeta57.tags) ? blogMeta57.tags : [],
  isPublished: blogMeta57.isPublished !== false,
  image: blogMeta57.image ? { filePath: blogMeta57.image } : undefined,
  headings: blogHeadings57,
  plainText: blogPlainText57,
  body: { raw: blogPlainText57 },
  Content: Blog57
},
{
  _id: "understanding-population-size-is-key-to-ux",
  slug: "understanding-population-size-is-key-to-ux",
  url: "/blogs/understanding-population-size-is-key-to-ux",
  title: blogMeta58.title,
  description: blogMeta58.description || "",
  publishedAt: blogMeta58.publishedAt,
  updatedAt: blogMeta58.updatedAt || blogMeta58.publishedAt,
  author: blogMeta58.author || "Hushh Team",
  tags: Array.isArray(blogMeta58.tags) ? blogMeta58.tags : [],
  isPublished: blogMeta58.isPublished !== false,
  image: blogMeta58.image ? { filePath: blogMeta58.image } : undefined,
  headings: blogHeadings58,
  plainText: blogPlainText58,
  body: { raw: blogPlainText58 },
  Content: Blog58
},
{
  _id: "unlock-the-power-of-your-data",
  slug: "unlock-the-power-of-your-data",
  url: "/blogs/unlock-the-power-of-your-data",
  title: blogMeta59.title,
  description: blogMeta59.description || "",
  publishedAt: blogMeta59.publishedAt,
  updatedAt: blogMeta59.updatedAt || blogMeta59.publishedAt,
  author: blogMeta59.author || "Hushh Team",
  tags: Array.isArray(blogMeta59.tags) ? blogMeta59.tags : [],
  isPublished: blogMeta59.isPublished !== false,
  image: blogMeta59.image ? { filePath: blogMeta59.image } : undefined,
  headings: blogHeadings59,
  plainText: blogPlainText59,
  body: { raw: blogPlainText59 },
  Content: Blog59
},
{
  _id: "unveiling-the-power-and-privacy-of-language-models-in-fashion",
  slug: "unveiling-the-power-and-privacy-of-language-models-in-fashion",
  url: "/blogs/unveiling-the-power-and-privacy-of-language-models-in-fashion",
  title: blogMeta60.title,
  description: blogMeta60.description || "",
  publishedAt: blogMeta60.publishedAt,
  updatedAt: blogMeta60.updatedAt || blogMeta60.publishedAt,
  author: blogMeta60.author || "Hushh Team",
  tags: Array.isArray(blogMeta60.tags) ? blogMeta60.tags : [],
  isPublished: blogMeta60.isPublished !== false,
  image: blogMeta60.image ? { filePath: blogMeta60.image } : undefined,
  headings: blogHeadings60,
  plainText: blogPlainText60,
  body: { raw: blogPlainText60 },
  Content: Blog60
},
{
  _id: "ux-can-boost-business-potential",
  slug: "ux-can-boost-business-potential",
  url: "/blogs/ux-can-boost-business-potential",
  title: blogMeta61.title,
  description: blogMeta61.description || "",
  publishedAt: blogMeta61.publishedAt,
  updatedAt: blogMeta61.updatedAt || blogMeta61.publishedAt,
  author: blogMeta61.author || "Hushh Team",
  tags: Array.isArray(blogMeta61.tags) ? blogMeta61.tags : [],
  isPublished: blogMeta61.isPublished !== false,
  image: blogMeta61.image ? { filePath: blogMeta61.image } : undefined,
  headings: blogHeadings61,
  plainText: blogPlainText61,
  body: { raw: blogPlainText61 },
  Content: Blog61
},
{
  _id: "voice-to-text-with-whisper",
  slug: "voice-to-text-with-whisper",
  url: "/blogs/voice-to-text-with-whisper",
  title: blogMeta62.title,
  description: blogMeta62.description || "",
  publishedAt: blogMeta62.publishedAt,
  updatedAt: blogMeta62.updatedAt || blogMeta62.publishedAt,
  author: blogMeta62.author || "Hushh Team",
  tags: Array.isArray(blogMeta62.tags) ? blogMeta62.tags : [],
  isPublished: blogMeta62.isPublished !== false,
  image: blogMeta62.image ? { filePath: blogMeta62.image } : undefined,
  headings: blogHeadings62,
  plainText: blogPlainText62,
  body: { raw: blogPlainText62 },
  Content: Blog62
},
{
  _id: "why-you-need-a-javaScript-module-bundler-in-my-chrome-extensions",
  slug: "why-you-need-a-javaScript-module-bundler-in-my-chrome-extensions",
  url: "/blogs/why-you-need-a-javaScript-module-bundler-in-my-chrome-extensions",
  title: blogMeta63.title,
  description: blogMeta63.description || "",
  publishedAt: blogMeta63.publishedAt,
  updatedAt: blogMeta63.updatedAt || blogMeta63.publishedAt,
  author: blogMeta63.author || "Hushh Team",
  tags: Array.isArray(blogMeta63.tags) ? blogMeta63.tags : [],
  isPublished: blogMeta63.isPublished !== false,
  image: blogMeta63.image ? { filePath: blogMeta63.image } : undefined,
  headings: blogHeadings63,
  plainText: blogPlainText63,
  body: { raw: blogPlainText63 },
  Content: Blog63
},
{
  _id: "you_dont_need_a_vector_database",
  slug: "you_dont_need_a_vector_database",
  url: "/blogs/you_dont_need_a_vector_database",
  title: blogMeta64.title,
  description: blogMeta64.description || "",
  publishedAt: blogMeta64.publishedAt,
  updatedAt: blogMeta64.updatedAt || blogMeta64.publishedAt,
  author: blogMeta64.author || "Hushh Team",
  tags: Array.isArray(blogMeta64.tags) ? blogMeta64.tags : [],
  isPublished: blogMeta64.isPublished !== false,
  image: blogMeta64.image ? { filePath: blogMeta64.image } : undefined,
  headings: blogHeadings64,
  plainText: blogPlainText64,
  body: { raw: blogPlainText64 },
  Content: Blog64
}].
filter((entry) => entry.isPublished);

export function getBlogBySlug(slug: string) {
  return allBlogs.find((blog) => blog.slug === slug) || null;
}

export const allBlogSummaries = allBlogs.map(({ Content: _Content, ...blog }) => blog);