/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx,html}",
    "./src/**/*.{html,js,jsx,ts,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        serif: ["Playfair Display", "serif"],
        manrope: ["Manrope", "sans-serif"],
      },
      colors: {
        "primary-accent": "#000000",
        "background-light": "#ffffff",
        "apple-gray": "#8E8E93",
        "apple-body": "#4B5563",
        "apple-card": "#F5F5F7",
        "premium-black": "#1D1D1F",
        "royal-charcoal": "#121214",
        "gold-accent": "#D4AF37",
        "growth-green": "#24B35E",
        "ios-blue": "#007AFF",
        richBlack: "#1A1A1B",
        mutedSlate: "#5F5F5F",
        yukonGold: "#C1A050",
        deepNavy: "#0A1128",
        offWhite: "#F9F9F9",
        mutedTaupe: "#8F8570",
        borderLight: "#F2F2F2",
        myBorder: "#606060",
        myBG: "black",
        headText: "#BEBEBF",
        normText: "rgba(101, 101, 101, 1)",
        speBG: "#5E2296",
        normBG: "#F8F0FF",
        lineGradient1: "#262626",
        lineGradient2: "#ADA785",
        lineGradient3: "#262626",
        fontColor5: "#E5E5E5",
        footerBG: "#363636",
        dark: "#1b1b1b",
        light: "#fff",
        accent: "#7B00D3",
        accentDark: "#ffdb4d",
        gray: "#747474",
        gradientColor1: "#E54D60",
        gradientColor2: "#A342FF",
        fontColor2: "#97A3B7",
        fontColor3: "#677489",
        gradientColor3: "#7A7A7E",
        fontColor4: "#ABABAB",
        faqBG: "#060606",
      },
      boxShadow: {
        premium: "0 10px 30px rgba(0, 0, 0, 0.03)",
      },
      animation: {
        "fade-in": "fadeIn 1s ease-in-out",
        fadeIn: "fadeIn 0.8s ease-in-out forwards",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: 0, transform: "translateY(10px)" },
          "100%": { opacity: 1, transform: "translateY(0)" },
        },
      },
    },
  },
  plugins: [
    require("@tailwindcss/typography"),
    require("@tailwindcss/forms"),
    require("@tailwindcss/aspect-ratio"),
    require("@tailwindcss/container-queries"),
  ],
  safelist: [
    { pattern: /hljs(-.*)?/ },
    "apple-code-block",
    "language-badge",
    "line-number",
    "highlighted",
  ],
};
