"use client";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: polyman (https://sketchfab.com/Polyman_3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/apple-iphone-15-pro-max-black-df17520841214c1792fb8a44c6783ee7
Title: Apple iPhone 17 Pro Max Black

Adapted from https://github.com/aksh10patil/iphone-17-pro
for Kai Discovery scroll-driven presentation.
*/

import * as THREE from "three";
import { useMemo } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import { useThree } from "@react-three/fiber";

export default function KaiIPhoneModel({ screenSrc, ...props }) {
  const { nodes, materials } = useGLTF("/models/scene.glb");
  const texture = useTexture(screenSrc);
  const maxAnisotropy = useThree((state) => state.gl.capabilities.getMaxAnisotropy());
  const tunedMaterials = useMemo(() => {
    const bodySilver = new THREE.Color("#d7dde7");
    const bodySilverDeep = new THREE.Color("#b7bfcc");
    const accentSilver = new THREE.Color("#eef2f7");
    const lensDark = new THREE.Color("#171b22");
    const lensRing = new THREE.Color("#8c93a1");
    const materialMap = {};
    const deepSilver = new Set([
      "PaletteMaterial002",
      "pIhYLPqiSQOZTjn",
      "jpGaQNgTtEGkTfo",
      "xNrofRCqOXXHVZt",
      "bCgzXjHOanGdTFV",
      "yiDkEwDSyEhavuP",
    ]);
    const brightSilver = new Set(["PaletteMaterial001", "TBLSREBUyLMVtJa", "jlzuBkUzuJqgiAK"]);
    const darkAccents = new Set(["PaletteMaterial003", "PaletteMaterial004"]);

    for (const [name, material] of Object.entries(materials)) {
      const nextMaterial = material.clone();

      const isScreenMaterial = name === "pIJKfZsazmcpEiU";
      const isDarkAccent = darkAccents.has(name);
      const isSilverSurface = !isScreenMaterial && !isDarkAccent;

      if ("color" in nextMaterial && nextMaterial.color) {
        if (isSilverSurface) {
          nextMaterial.color.copy(
            brightSilver.has(name) ? accentSilver : deepSilver.has(name) ? bodySilverDeep : bodySilver
          );
        } else if (isDarkAccent) {
          nextMaterial.color.copy(lensDark);
        }
      }

      if ("metalness" in nextMaterial) {
        nextMaterial.metalness = isSilverSurface ? 0.9 : isDarkAccent ? 0.48 : nextMaterial.metalness;
      }

      if ("roughness" in nextMaterial) {
        nextMaterial.roughness = isSilverSurface ? 0.21 : isDarkAccent ? 0.18 : nextMaterial.roughness;
      }

      if ("envMapIntensity" in nextMaterial) {
        nextMaterial.envMapIntensity = isSilverSurface ? 1.7 : 1.15;
      }

      if ("clearcoat" in nextMaterial) {
        nextMaterial.clearcoat = isSilverSurface ? 0.75 : nextMaterial.clearcoat;
      }

      if ("clearcoatRoughness" in nextMaterial) {
        nextMaterial.clearcoatRoughness = isSilverSurface ? 0.12 : nextMaterial.clearcoatRoughness;
      }

      if (darkAccents.has(name) && "emissive" in nextMaterial && nextMaterial.emissive) {
        nextMaterial.emissive.copy(lensRing);
        nextMaterial.emissiveIntensity = 0.02;
      }

      nextMaterial.needsUpdate = true;
      materialMap[name] = nextMaterial;
    }

    return materialMap;
  }, [materials]);
  const screenTexture = useMemo(() => {
    const nextTexture = texture.clone();
    nextTexture.colorSpace = THREE.SRGBColorSpace;
    nextTexture.anisotropy = maxAnisotropy;
    nextTexture.minFilter = THREE.LinearMipmapLinearFilter;
    nextTexture.magFilter = THREE.LinearFilter;
    nextTexture.generateMipmaps = true;
    nextTexture.needsUpdate = true;
    return nextTexture;
  }, [maxAnisotropy, texture]);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ttmRoLdJipiIOmf.geometry}
        material={tunedMaterials.hUlRcbieVuIiOXG}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.DjsDkGiopeiEJZK.geometry}
        material={tunedMaterials.PaletteMaterial001}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.buRWvyqhBBgcJFo.geometry}
        material={tunedMaterials.PaletteMaterial002}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MrMmlCAsAxJpYqQ_0.geometry}
        material={tunedMaterials.dxCVrUCvYhjVxqy}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wqbHSzWaUxBCwxY_0.geometry}
        material={tunedMaterials.MHFGNLrDQbTNima}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.QvGDcbDApaGssma.geometry}
        material={tunedMaterials.kUhjpatHUvkBwfM}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.vFwJFNASGvEHWhs.geometry}
        material={tunedMaterials.RJoymvEsaIItifI}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.evAxFwhaQUwXuua.geometry}
        material={tunedMaterials.KSIxMqttXxxmOYl}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.USxQiqZgxHbRvqB.geometry}
        material={tunedMaterials.mcPrzcBUcdqUybC}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TvgBVmqNmSrFVfW.geometry}
        material={tunedMaterials.pIhYLPqiSQOZTjn}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GuYJryuYunhpphO.geometry}
        material={tunedMaterials.eShKpuMNVJTRrgg}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pvdHknDTGDzVpwc.geometry}
        material={tunedMaterials.xdyiJLYTYRfJffH}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CfghdUoyzvwzIum.geometry}
        material={tunedMaterials.jpGaQNgTtEGkTfo}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.DjdhycfQYjKMDyn.geometry}
        material={tunedMaterials.ujsvqBWRMnqdwPx}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.usFLmqcyrnltBUr.geometry}
        material={tunedMaterials.sxNzrmuTqVeaXdg}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.xXDHkMplTIDAXLN.geometry}
        material={materials.pIJKfZsazmcpEiU}
        scale={0.01}
      >
        <meshBasicMaterial
          map={screenTexture}
          toneMapped={false}
          side={THREE.FrontSide}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.vELORlCJixqPHsZ.geometry}
        material={tunedMaterials.zFdeDaGNRwzccye}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.EbQGKrWAqhBHiMv.geometry}
        material={tunedMaterials.TBLSREBUyLMVtJa}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.EddVrWkqZTlvmci.geometry}
        material={tunedMaterials.xNrofRCqOXXHVZt}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.KSWlaxBcnPDpFCs.geometry}
        material={tunedMaterials.yQQySPTfbEJufve}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TakBsdEjEytCAMK.geometry}
        material={tunedMaterials.PaletteMaterial003}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.IykfmVvLplTsTEW.geometry}
        material={tunedMaterials.PaletteMaterial004}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wLfSXtbwRlBrwof.geometry}
        material={tunedMaterials.oZRkkORNzkufnGD}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WJwwVjsahIXbJpU.geometry}
        material={tunedMaterials.yhcAXNGcJWCqtIS}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.YfrJNXgMvGOAfzz.geometry}
        material={tunedMaterials.bCgzXjHOanGdTFV}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.DCLCbjzqejuvsqH.geometry}
        material={tunedMaterials.vhaEJjZoqGtyLdo}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CdalkzDVnwgdEhS.geometry}
        material={tunedMaterials.jlzuBkUzuJqgiAK}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NtjcIgolNGgYlCg.geometry}
        material={tunedMaterials.PpwUTnTFZJXxCoE}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pXBNoLiaMwsDHRF.geometry}
        material={tunedMaterials.yiDkEwDSyEhavuP}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.IkoiNqATMVoZFKD.geometry}
        material={tunedMaterials.hiVunnLeAHkwGEo}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rqgRAGHOwnuBypi.geometry}
        material={tunedMaterials.HGhEhpqSBZRnjHC}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload("/models/scene.glb");
