'use client';
import { useState, useEffect } from 'react';
import AuthGate from '../components/AuthGate';
import BottomNav from '../components/BottomNav';
import CardStack from '../components/CardStack';
import MatchToast from '../components/MatchToast';
import { useSwipe } from '../context/SwipeContext';
import '../investor-match.css';

export default function DiscoverPage() {
  const { swipes, handleLike, handlePass } = useSwipe();
  const [investors, setInvestors] = useState([]);
  const [loading, setLoading] = useState(true);
  const [matchedInvestor, setMatchedInvestor] = useState(null);

  useEffect(() => {
    // Fetch investor data (generated by node scripts/convertInvestorData.js)
    async function loadData() {
      try {
        const res = await fetch('/investorData.json');
        if (!res.ok) throw new Error('Failed to fetch investor data');
        const data = await res.json();
        
        // Filter out those already swiped (either liked or passed)
        const unswiped = data.filter(
          (inv) => !swipes.liked.includes(inv.id) && !swipes.passed.includes(inv.id)
        );
        
        // Shuffle the array for a random discovery feed
        const shuffled = unswiped.sort(() => Math.random() - 0.5);
        
        setInvestors(shuffled);
      } catch (e) {
        console.error('Error loading investors:', e);
      } finally {
        setLoading(false);
      }
    }
    loadData();
  }, [swipes.liked, swipes.passed]);

  const onLike = (id) => {
    handleLike(id);
    
    // Simulate a match logic (e.g. 10% chance to match with any investor)
    const isMatch = Math.random() > 0.9;
    if (isMatch) {
      const matchObj = investors.find(i => i.id === id);
      setMatchedInvestor(matchObj);
    }
  };

  const onPass = (id) => {
    handlePass(id);
  };

  return (
    <AuthGate>
      <div className="im-container">
        {/* Header */}
        <header className="im-header">
          <div className="im-header-title">
            <img src="/svgs/hushhEmoji.svg" alt="Hushh" style={{ width: 32, height: 32 }} />
            <span>Discover</span>
          </div>
          <div className="im-header-actions">
            <button aria-label="Filters">⚙️</button>
          </div>
        </header>

        {/* Main Swipe Area */}
        <main className="im-main">
          {loading ? (
            <div className="im-loading-screen">
              <div className="im-loader-ring" />
              <p className="im-loading-text">Finding Investors...</p>
            </div>
          ) : (
            <CardStack investors={investors} onLike={onLike} onPass={onPass} />
          )}
        </main>

        <BottomNav />

        {/* Match Notification Overlay */}
        {matchedInvestor && (
          <MatchToast 
            investor={matchedInvestor} 
            onClose={() => setMatchedInvestor(null)} 
          />
        )}
      </div>
    </AuthGate>
  );
}
