export const SUPABASE_URL = "https://ibsisfnjxeowvdtvgzff.supabase.co";
export const SUPABASE_ANON_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlic2lzZm5qeGVvd3ZkdHZnemZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ1NTk1NzgsImV4cCI6MjA4MDEzNTU3OH0.K16sO1R9L2WZGPueDP0mArs2eDYZc-TnIk2LApDw_fs";
export const FUNCTIONS_BASE = `${SUPABASE_URL}/functions/v1`;
export const TEST_EMAIL = "plaid-test@hushh.ai";
export const TEST_PASSWORD = "TestPlaid2026!";

export const TABS = [
  { id: "overview", label: "Overview" },
  { id: "live-test", label: "Live Test" },
  { id: "api-docs", label: "API Docs" },
  { id: "api-tester", label: "API Tester" },
  { id: "architecture", label: "Architecture" },
  { id: "use-cases", label: "Use Cases" },
];

export const s = {
  page: {
    minHeight: "100vh",
    backgroundColor: "#0a0a0a",
    color: "#e0e0e0",
    fontFamily: 'ui-monospace, "SF Mono", Menlo, monospace',
    padding: 0,
  },
  topBar: {
    background: "linear-gradient(90deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)",
    padding: "12px 24px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottom: "1px solid #1e3a5f",
  },
  tabBar: {
    display: "flex",
    gap: 0,
    borderBottom: "1px solid #222",
    backgroundColor: "#111",
    overflowX: "auto",
  },
  tab: (active) => ({
    padding: "12px 20px",
    fontSize: 13,
    fontWeight: active ? 700 : 400,
    color: active ? "#60a5fa" : "#888",
    backgroundColor: active ? "#1a1a2e" : "transparent",
    border: "none",
    borderBottom: active ? "2px solid #60a5fa" : "2px solid transparent",
    cursor: "pointer",
    whiteSpace: "nowrap",
  }),
  container: { maxWidth: 1100, margin: "0 auto", padding: "24px 20px" },
  card: {
    border: "1px solid #222",
    borderRadius: 8,
    padding: 24,
    marginBottom: 20,
    backgroundColor: "#111",
  },
  cardActive: {
    border: "1px solid #22c55e33",
    borderRadius: 8,
    padding: 24,
    marginBottom: 20,
    backgroundColor: "#0a1a0a",
  },
  h2: { fontSize: 18, fontWeight: 700, marginBottom: 12, color: "#fff" },
  desc: { fontSize: 13, color: "#888", marginBottom: 16, lineHeight: 1.6 },
  btn: (disabled) => ({
    padding: "10px 20px",
    backgroundColor: disabled ? "#333" : "#2563eb",
    color: "#fff",
    border: "none",
    borderRadius: 6,
    fontSize: 13,
    fontWeight: 600,
    cursor: disabled ? "default" : "pointer",
    opacity: disabled ? 0.5 : 1,
  }),
  btnGreen: {
    padding: "10px 20px",
    backgroundColor: "#22c55e",
    color: "#000",
    border: "none",
    borderRadius: 6,
    fontSize: 13,
    fontWeight: 700,
  },
  code: {
    backgroundColor: "#1a1a2e",
    border: "1px solid #2a2a4e",
    borderRadius: 6,
    padding: 16,
    fontSize: 12,
    lineHeight: 1.6,
    overflowX: "auto",
    color: "#e0e0e0",
    fontFamily: 'ui-monospace, "SF Mono", Menlo, monospace',
    whiteSpace: "pre-wrap",
    wordBreak: "break-all",
  },
  label: { fontSize: 11, color: "#666", textTransform: "uppercase", letterSpacing: 1, marginBottom: 4 },
  value: { fontSize: 16, fontWeight: 700, color: "#fff" },
  grid2: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16 },
  input: {
    width: "100%",
    padding: "8px 12px",
    backgroundColor: "#1a1a2e",
    border: "1px solid #333",
    borderRadius: 4,
    color: "#e0e0e0",
    fontSize: 13,
    fontFamily: "monospace",
    boxSizing: "border-box",
  },
  textarea: {
    width: "100%",
    padding: "8px 12px",
    backgroundColor: "#1a1a2e",
    border: "1px solid #333",
    borderRadius: 4,
    color: "#e0e0e0",
    fontSize: 12,
    fontFamily: "monospace",
    boxSizing: "border-box",
    minHeight: 100,
    resize: "vertical",
  },
  select: {
    padding: "8px 12px",
    backgroundColor: "#1a1a2e",
    border: "1px solid #333",
    borderRadius: 4,
    color: "#e0e0e0",
    fontSize: 13,
  },
  badge: (color) => ({
    fontSize: 10,
    padding: "3px 8px",
    borderRadius: 4,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: 1,
    backgroundColor: color,
    color: "#000",
    display: "inline-block",
  }),
  dot: (ok) => ({
    width: 8,
    height: 8,
    borderRadius: "50%",
    backgroundColor: ok ? "#22c55e" : "#ef4444",
    display: "inline-block",
    marginRight: 8,
  }),
  sectionTitle: { fontSize: 14, fontWeight: 700, color: "#60a5fa", marginBottom: 12, textTransform: "uppercase", letterSpacing: 1 },
};
